spring:
  application:
    name: estudiantes-service

  datasource:
    url: jdbc:postgresql://localhost:5432/schooldb
    username: julianortizcastaneda
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka