server:
  port: 9000

spring:
  application:
    name: schoolapigateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: personas-api
          uri: lb://personas-service
          predicates:
            - Path=/api/personas/**
          filters:
            - RewritePath=/api/personas(?<segment>.*), /${segment}
        - id: estudiantes-api
          uri: lb://estudiantes-service
          predicates:
            - Path=/api/estudiantes/**
          filters:
            - RewritePath=/api/estudiantes(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka